### ISSUE TITLE
[Suggestion] Filter by date

### ISSUE THREAD

**Issue by vigiraud** [Lyfhael/DeleteTweets#3]
Hi, thanks for this project.
It would be really great if one could filter the tweets to delete depending on the date. For example, being able to set a rule like «delete all the tweets older than 6 months».

**Comment by teisseire117** [comment]
next in my to-do list

**Comment by titodelas** [comment]
Adding an option to filter tweets by date in your existing JavaScript code can be a bit complex because Twitter's API does not provide direct filtering by date. However, you can modify your script to filter tweets by their creation date after fetching them. Here's how you can do that:

1. Add a `filterByDate` function to filter tweets by date. This function will take the `entries` (tweet data) as input and return filtered entries based on the date range you specify.

```javascript
function filterByDate(entries, startDate, endDate) {
  return entries.filter((tweet) => {
    const createdAt = new Date(tweet["legacy"]["created_at"]);
    return createdAt >= startDate && createdAt <= endDate;
  });
}
```

2. Define your desired date range by creating `startDate` and `endDate` objects. For example, to filter tweets from January 1, 2023, to February 28, 2023:

```javascript
const startDate = new Date("2023-01-01T00:00:00Z");
const endDate = new Date("2023-02-28T23:59:59Z");
```

3. Modify your main loop to include date filtering. After fetching tweets using `fetch_tweets`, use the `filterByDate` function to filter the tweets based on the date range:

```javascript
entries = await fetch_tweets(next);
entries = filterByDate(entries, startDate, endDate); // Apply date filtering
next = await log_tweets(entries);
await delete_tweets(tweets_to_delete);
tweets_to_delete = [];
await sleep(3000);
```

With these modifications, your script will fetch tweets and then filter them to include only those that fall within the specified date range. Make sure to adjust the `startDate` and `endDate` to match your desired date filtering criteria.

**Comment by titodelas** [comment]
I don't know if it works, it's just theory. I hope it can help you ;)

**Comment by Lyfhael** [comment]
> I don't know if it works, it's just theory. I hope it can help you ;)

done, I added explanation how to do it in the readme :)
