### ISSUE TITLE
Deletion complete, but tweets remain from 2018 and earlier

### ISSUE THREAD

**Issue by samhurst** [Lyfhael/DeleteTweets#7]
Hi there,

Thanks for the really useful tool, but I've hit a problem where it doesn't seem to be able to remove any tweets that were made before the middle of 2018. On the console, it counts down (3) ..., (2) ..., (1)..., DELETION COMPLETE, but even though there are no errors my very old tweets remain.

I'm using the latest version of Chrome (116.0.5845.180).

Let me know what info you need from me to reproduce/debug.

Best,
-Sam

**Comment by samhurst** [comment]
I should mention that it has done this on two separate Twitter accounts. Thankfully one of them only had Tweets starting in early 2018, but another has tweets going all the way back to ~2009, so clearing out the last ones by hand isn't really ideal.

**Comment by Lyfhael** [comment]
I would need to know your account name so I can see what sort of object Twitter returns for these old tweets. You can send in discord DM if you want : Lyfhael

**Comment by samhurst** [comment]
Sure, my account name on there is @ SoshDragon

The only errors I get on the console are when the page first loads, where I get a load of warnings about "DevTools failed to load source map: Could not load content for https://ton.local.twitter.com/...". I think this is a DNS issue.

Other than that, nothing. This is what the console looks like when I run the script now after it's deleted everything up to mid-August 2018.

![image](https://github.com/Lyfhael/DeleteTweets/assets/9945958/872a7cb5-38b7-4414-be5c-a67b5fc89add)

**Comment by Lyfhael** [comment]
Oh, I see. Looking at your Replies tab on your Twitter no tweets are showing. That's what the script feeds on to find tweets so it rightfully says it finished.
But for you some tweets appear in Posts tab but not in the Replies one. Which is different for some other people, but I guess as you mentioned it must be due to the date of the tweets, Twitter must have made some changes along the way and didn't normalize everything properly.

I'll adapt the script and post it later either this evening or tomorrow

**Comment by Lyfhael** [comment]
Alright it should be good. Get the last version of the script, and set "old_tweets":false to true

**Comment by samhurst** [comment]
Many thanks, that's fixed the issue for me. :)
